google_place_field.settings:
  type: config_object
  label: 'Google Place Field settings'
  mapping:
    api_key:
      type: string
      label: 'Google API Key'

    field_masks:
      type: sequence
      label: 'Google Places field masks'
      sequence:
        type: string

field.storage_settings.google_place_field_google_business:
  type: mapping
  label: Google Business storage settings
  mapping:
    foo:
      type: string
      label: Foo

field.field_settings.google_place_field_google_business:
  type: mapping
  label: Google Business field settings
  mapping:
    bar:
      type: string
      label: Bar

field.value.google_place_field_google_business:
  type: mapping
  label: Default value
  mapping:
    value:
      type: label
      label: Value
