<?php

/**
 * @file
 * Primary module hooks for Google Place Field module.
 */

function google_place_field_theme(): array {
  return [
    'google_place_rating' => [
      'variables' => ['rating' => NULL],
      'template' => 'google-place-rating',
    ],
    'google_place_reviews' => [
      'variables' => ['reviews' => []],
      'template' => 'google-place-reviews',
    ],
    'google_place_map' => [
      'variables' => ['map_url' => NULL],
      'template' => 'google-place-map',
    ],
    'google_place_display_name' => ['variables' => ['detail' => NULL]],
    'google_place_user_rating_count' => ['variables' => ['detail' => NULL]],
    'google_place_address' => ['variables' => ['detail' => NULL]],
    'google_place_phone' => ['variables' => ['detail' => NULL]],
    'google_place_website' => ['variables' => ['detail' => NULL]],
    'google_place_maps_uri' => ['variables' => ['detail' => NULL]],
    'google_place_full' => ['variables' => ['detail' => NULL]],
    'google_place_reviews_no_summary' => ['variables' => ['reviews' => NULL],
      'template' => 'google-place-reviews-no-summary'],
  ];
}
